INSERT INTO `odelice`.`recette` (`Titre`, `Cuisson`, `Repos`, `Difficulte`, `Preparation`) 
VALUES ('Pancake', '10 min', '30 min', 'Facile', 'POUR PANCAKES À LA VANILLE ET AU SUCRE ROUX STÉVIA\nPancakes à la vanille et au sucre roux Stévia\n\n1. Dans un saladier, mélangez le beurre fondu, le lait et l’oeuf battu.\n2. Dans un autre récipient mêlez la farine, la levure, le Sucre Roux & Stevia* Pure Via, et les graines de vanille.\n3. Mélangez les deux appareils de manière harmonieuse afin d’obtenir une belle pâte à pancakes sans grumeaux.\n4. Réservez la pâte 2 heures à température ambiante.\n5. Dans une poêle à blinis huilée au moyen d’un pinceau (ou d’un papier essuie-tout), déposez une louche de pâte et laissez cuire chaque côté 2 minutes environ.\n\nCompotée de prunes :\n\n1. Dans une sauteuse, faites fondre le beurre puis ajoutez-y les prunes, poudrez de Sucre Roux & Stevia* Pure Via et de cannelle.\n\n2. Faites revenir pendant une dizaine de minutes tout en mélangeant fréquemment.\n\nConseils :\nA défaut de poêle à blinis, faites chauffer une grande poêle huilée, versez-y quatre petites louches de pâte et faites cuire de la même manière.\nFaites attention à ce que la chaleur soit bien répartie pour éviter que les pancakes ne brûlent avant d’être cuits.\nLa pâte doit être bien cuite avant de retourner les pancakes. Trop liquide, elle se répandrait et déformerait le pancake.');
INSERT INTO `odelice`.`recette` (`Titre`, `Cuisson`, `Repos`, `Difficulte`, `Image`, `Preparation`) 
VALUES ('SALADE DE CALAMARS GRILLÉS', 'Cuisson : 15 min\n', '-', 'Facile', 'https://odelices.ouest-france.fr/images/recettes/suzi-wan-salade-calamars-grilles-500x669.jpg', '1.  Réalisez dans un premier temps la sauce. Pour ce faire, mélangez dans un bol l’huile d’arachide avec le jus de citron vert, les piments émincés et enfin la sauce soja.\n\n2. Dans une petite poêle, faites revenir l’ail pelé et finement émincé avec 2 cuillerées à soupe d’huile d’olive. Ajoutez l’ail à la sauce et réservez.\n3. Lavez puis effeuillez la menthe et le basilic thaï. Pelez, lavez puis coupez en tranches fines le concombre. Déposez le tout dans un saladier.\n4. Faites saisir les calamars très rapidement dans une poêle avec 1 cuillerée à soupe d’huile d’olive à feu vif. Une fois une belle coloration dorée obtenue, déposez les morceaux de calamars dans 6 assiettes, puis décorez avec la salade de concombres et herbes. Arrosez le tout de sauce au soja et ajoutez quelques cacahuètes concassées.');
INSERT INTO `odelice`.`recette` (`Titre`, `Cuisson`, `Repos`, `Difficulte`, `Image`, `Preparation`) 
VALUES ('CAKE DÉLICIEUX AU TOFU ET TOMATES – VEGAN', '50', '-', 'Très facile', 'https://odelices.ouest-france.fr/images/recettes/cake-vegan-tofu-tossolia1-683x1024.jpg', '1. Coupez en cubes les tomates ainsi que le tofu. Réservez-les.\n2. Dans un saladier, mélangez les ingrédients secs ensemble : farine, fécule de maïs, levure, herbes de Provence, sel et poivre.\n3. Versez ensuite progressivement les ingrédients liquides en battant au fouet.\n4. Une fois la préparation bien homogène, incorporez les tomates et le tofu. Mélangez délicatement.\n5. Versez la préparation dans un moule à cake puis placez-le au four préchauffé à 180 °C pour 50 min environ.\n6. Démoulez le cake à la sortie du four. À déguster froid ou tiède.');
INSERT INTO `odelice`.`recette` (`Titre`, `Cuisson`, `Repos`, `Difficulte`, `Image`, `Preparation`) 
VALUES ('CAKE AU POTIMARRON ET AUX NOISETTES', '10 min', '45 min', 'Facile', 'https://odelices.ouest-france.fr/images/recettes/soy_cake_potimarron_noisettes.jpg', '1. Mélangez la farine, la poudre à lever et les épices dans un saladier.\n2. Dans un second saladier, fouettez le tofu soyeux avec la purée de potimarron et l’huile. Ajoutez au 1er saladier, mélangez bien.\n3. Coupez le tofu en petits dés et concasssez les noisettes puis incorporez dans la pate à cake.\n4. Salez, poivrez et versez dans un moule à cake.\n5. Enfourner 45 min à 180°C (Th.6).');
INSERT INTO `odelice`.`recette` (`Titre`, `Cuisson`, `Repos`, `Difficulte`, `Image`, `Preparation`) 
VALUES ('SALADE BOWL', '10', '-', 'Difficile', 'https://odelices.ouest-france.fr/images/recettes/salade-bowl-puree-de-lentilles-corail-poulet-grille-et-avocat-500x333.jpg', 'Laver les lentilles puis les cuire dans 50 cl d’eau froide avec la branche de thym. Amener à ébullition et cuire 10 minutes. Egoutter puis réduire en purée après avoir retiré la branche de thym. Saler, poivrer.\n\nDétailler de très fines tranches de betteraves crues. Couper les tomates cerise en 2. Couper les avocats en lamelles et les arroser de jus de citron pour éviter qu’ils ne noircissent.\n\nCuire le poulet dans un peu d’huile jusqu’à ce qu’il soit cuit et bien doré de chaque côté. Découper en morceaux.\n\nMonter le salad bowl en déposant dans chaque assiette du poulet, des jeunes pousses agrémentées de tomates cerise, de la purée de lentilles corail, de l’avocat et de la betterave crue. Arroser de jus de citron et d’huile d’olive. Parsemer de sel, de poivre et de sésame noir.');


INSERT INTO `odelice`.`commentaire` (`texte`, `auteur`, `email`, `note`,`idRecette`) 
VALUES 
('Commentaire lambda','Auteur', 'email@email.mail','1','1'),
('Commentaire lambda','shsfh', 'email@email.mail','2','2'),
('Commentaire lambda','sthhsfj', 'email@email.mail','3','3'),
('Commentaire lambda','ytifyui', 'email@email.mail','4','4'),
('Commentaire lambda','sqegfsdrg', 'email@email.mail','2','5'),
('Commentaire lambda','vncgj', 'email@email.mail','3','1'),
('Commentaire lambda','Authghgheur', 'email@email.mail','5','2'),
('Commentaire lambda','eerg', 'email@email.mail','5','3'),
('Commentaire lambda','Autfyuyeur', 'email@email.mail','7','4'),
('Commentaire lambda','Auterzdeur', 'email@email.mail','9','5'),
('Commentaire lambda','gfngyj', 'email@email.mail','9','1');